name: Generar APK Android Nativo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Compilar APK
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Descargar repositorio
        uses: actions/checkout@v4

      - name: 🏗️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Instalar dependencias JS
        run: npm install

      - name: ☕ Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🔑 Dar permisos a Gradle
        run: chmod +x android/gradlew

      # Forzamos a Gradle y al empaquetador a usar el entorno de Node 20 activo
      - name: 🤖 Compilar APK Nativo
        env:
          NODE_ENV: production
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease